# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RadioButtonTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RadioButtonTest

  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'

  target 'RadioButtonTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RadioButtonTestUITests' do
    # Pods for testing
  end

end
